Bootstrap: docker
From: ubuntu

%setup
     ## The "%setup"-part of this script is called to bootstrap an empty
     ## container. It copies the source files from the branch of your
     ## repository where this file is located into the container to the
     ## directory "/planner". Do not change this part unless you know
     ## what you are doing and you are certain that you have to do so.

    REPO_ROOT=`dirname $SINGULARITY_BUILDDEF`
    cp -r $REPO_ROOT/ $SINGULARITY_ROOTFS/planner

%post

    ## The "%post"-part of this script is called after the container has
    ## been created with the "%setup"-part above and runs "inside the
    ## container". Most importantly, it is used to install dependencies
    ## and build the planner. Add all commands that have to be executed
    ## once before the planner runs in this part of the script.

    ## Install all necessary dependencies.
	## dependencies siw bsf
	apt-get update
	apt-get install --no-install-recommends -y --no-install-recommends apt-utils\
	build-essential \
	g++\
	gcc\
	make\
	cmake\
	python\
	ca-certificates \
	xutils-dev \
	scons \
	gcc-multilib \
	flex \
	bison \
	python3 \
	libboost-dev \
	libjudy-dev \
	libboost-program-options-dev \
	g++-multilib \
	libgmp3-dev \
	gawk\
	pypy\
	python-pyparsing\
	python-psutil\
	libncurses5-dev	
	
	
    ## Build 
    ./planner/build

%runscript
    ## The runscript is called whenever the container is used to solve
    ## an instance.

    DOMAINFILE=$1
    PROBLEMFILE=$2
    PLANFILE=$3
    ## Call your planner.
    python2.7 /planner/src/launcher/solve.py "$DOMAINFILE" "$PROBLEMFILE" "$PLANFILE"

		
## Update the following fields with meta data about your submission.
## Please use the same field names and use only one line for each value.
%labels
Name        TemPorAl
Description Temporal Portfolio Algorithm
Authors     Isabel Cenamor <icenamorg@gmail.com>, Mauro Vallati <m.vallati@hud.ac.uk>, Lukas Chrpa <chrpaluk@fel.cvut.cz>, Tomas de la Rosa <trosa@inf.uc3m.es> and  Fernando Fernandez <ffernand@inf.uc3m.es>

